services:
  etcd1:
    image: quay.io/coreos/etcd:v3.5.15
    container_name: etcd1-work
    restart: always
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ETCD_NAME=etcd1
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER_STATE=new
    volumes:
      - ./data/etcd1:/etcd_data
    networks:
      - app_network

  etcd2:
    image: quay.io/coreos/etcd:v3.5.15
    container_name: etcd2-work
    restart: always
    ports:
      - "2381:2379"
      - "2382:2380"
    environment:
      - ETCD_NAME=etcd2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER_STATE=new
    volumes:
      - ./data/etcd2:/etcd_data
    networks:
      - app_network

  etcd3:
    image: quay.io/coreos/etcd:v3.5.15
    container_name: etcd3-work
    restart: always
    ports:
      - "2383:2379"
      - "2384:2380"
    environment:
      - ETCD_NAME=etcd3
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd3:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd3:2379
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER_STATE=new
    volumes:
      - ./data/etcd3:/etcd_data
    networks:
      - app_network

  mysql:
    image: mysql:5.7
    container_name: mysql-work
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - app_network
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
    networks:
      - app_network

  nsqlookupd:
    image: nsqio/nsq:latest
    container_name: nsqlookupd
    restart: always
    ports:
      - "4160:4160"
      - "4161:4161"
    command: /nsqlookupd
    networks:
      - app_network

  nsqd:
    image: nsqio/nsq:latest
    container_name: nsqd
    restart: always
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
    command: >
      /nsqd
      --lookupd-tcp-address=nsqlookupd:4160
      --broadcast-address=host.docker.internal
    volumes:
      - ./data/nsq:/data
    networks:
      - app_network

  nsqadmin:
    image: nsqio/nsq:latest
    container_name: nsqadmin
    restart: always
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  nsq_data: 
  etcd1_data:
  etcd2_data:
  etcd3_data: